version: "3"

services:
  backend:
    build: ./backend
    container_name: blog_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    links:
      - db

  frontend:
    build: ./frontend
    container_name: blog_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - .:/frontend/nginx.conf:ro
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: blog_nginx
    ports:
      - "80"
    depends_on:
      - backend

  db:
    image: mongo:latest
    hostname: userdb
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./backend/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    container_name: blog_mongodb
    ports:
      - "27017:27017"
